apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
spec:
  selector:
    matchLabels:
      app: spring-boot-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
      - name: spring-boot-demo
        image: spring-boot-demo-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-demo
