apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-demo
  name: spring-demo-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: spring-demo
